# Reference
# - https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp

matrix:
  include:
    - os: osx
      env: COMPILER=g++-6
    - os: osx
      env: COMPILER=clang++-5.0
    - os: linux
      env: COMPILER=g++-6
      addons:
        apt:
          packages:
            - xorg-dev
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      env: COMPILER=clang++-5.0
      addons:
        apt:
          packages:
            - xorg-dev
            - clang-5.0
          sources:
            - llvm-toolchain-trusty-5.0

env:
  global:
    - PREMAKE_VERSION="5.0.0-alpha12"
  linux:
    - JOBS="$(nproc)"  # should be ~2
  osx:
    - JOBS="$(sysctl -n hw.ncpu)"  # should be 2

cache:
  apt: true  # private repositories only
  directories:
    - premake-${PREMAKE_VERSION}

install:
  # Set the ${CXX} variable properly (don't do it in env, it is too early and would be overriden by compiler settings just afterward)
  - export CXX=${COMPILER}
  - ${CXX} --version

  # if premake source has not been downloaded or built with the right version, download it and build it now
  - wget "https://github.com/premake/premake-core/releases/download/v${PREMAKE_VERSION}/premake-${PREMAKE_VERSION}-src.zip"
  - |
    if [[ -z "$(ls -A premake-${PREMAKE_VERSION})" || ! -x "$HOME/bin/premake5" || "$(premake5 --version)" == *"${PREMAKE_VERSION}" ]]; then
      rm -rf "premake-${PREMAKE_VERSION}"
      unzip "premake-${PREMAKE_VERSION}-src.zip"
      if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        PREMAKE_BUILD_DIR="gmake.unix"
      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        PREMAKE_BUILD_DIR="gmake.macosx"
      fi
    fi
  - pushd "premake-${PREMAKE_VERSION}/build/${PREMAKE_BUILD_DIR}"
  - make ${MAKEFLAGS}
  - popd
  - mkdir "$HOME/bin" -p
  - cp "premake-${PREMAKE_VERSION}/bin/release/premake5" "$HOME/bin/premake5"

before_script:
  # build Box2D
  - pushd "third-party/Box2D/Box2D"
  - premake5 gmake
  - pushd "Build/gmake"
  - export config=release
  - make Box2D ${MAKEFLAGS}  # we don't need to build the examples
  - popd
  - popd

script:
  - mkdir -p build/release
  - cd build/release
  - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CXX_COMPILER_ID=${CMAKE_CXX_COMPILER_ID} -DBUILD_TESTS=ON ../.. -j${JOBS}
  - make -j${JOBS}
  - ctest --output-on-failure -j${JOBS}

